### PR TITLE
add pull request template

### PR DESCRIPTION
**Pull request by Aki-7**
## Context

See #7.

## Summary

Add a pull request template

@shierote @liwii 
Could you review this again?
Comparing to https://github.com/zigen-project/zen/pull/77, I added a new part that describe the context, which may include related issues.

### CODE REVIEW

**Comment by watasuke102** [comment]
Adding section about environment (hardware, software, etc) seems work well.

**Comment by Aki-7** [comment]
For pull request?
You mean we should add a subsection like "env" to "How to check behavior" section?

**Comment by watasuke102** [comment]
I misunderstood this as issue template.

**Review by watasuke102 — APPROVED** [review]

**Review by shierote — APPROVED** [review]
looks good!

**Pull request merged**
